# Generated by Django 4.2 on 2024-10-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_rename_education_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summary",
            name="summary",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
