# Generated by Django 4.2 on 2024-10-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_skill_delete_skills"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workexperience",
            name="present",
        ),
    ]
