# Generated by Django 4.2 on 2024-10-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_contactinformation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactinformation",
            name="cv",
        ),
    ]
