# Generated by Django 4.2 on 2024-10-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_remove_workexperience_present"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="location",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
