# Generated by Django 4.2 on 2024-10-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_remove_workexperience_present"),
    ]

    operations = [
        migrations.AddField(
            model_name="workexperience",
            name="applied_skills",
            field=models.ManyToManyField(
                related_name="work_experience", to="profiles.skill"
            ),
        ),
    ]
