# Generated by Django 4.2 on 2024-10-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_education_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="workexperience",
            name="location",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
