# Generated by Django 4.2 on 2024-10-14 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_workexperience_applied_skills"),
        ("profiles", "0005_workexperience_location"),
    ]

    operations = []
