# Generated by Django 4.2 on 2024-10-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_merge_20241014_0903"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="end_year",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="start_year",
            field=models.DateField(),
        ),
    ]
