# Generated by Django 4.2 on 2024-10-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_alter_education_end_year_alter_education_start_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="applied_skills",
            field=models.ManyToManyField(to="profiles.skill"),
        ),
    ]
