# Generated by Django 4.2 on 2024-10-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_project"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="reposity_url",
            new_name="repository_url",
        ),
    ]
