# Generated by Django 4.2 on 2024-10-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0010_rename_reposity_url_project_repository_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="deployed_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
