# Generated by Django 4.2 on 2024-10-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0011_alter_project_deployed_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="grade",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
