# Generated by Django 4.2 on 2024-10-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0013_alter_education_applied_skills_and_more"),
        ("profiles", "0013_project_description"),
    ]

    operations = []
