# Generated by Django 4.2 on 2024-10-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0014_merge_20241016_1705"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summary",
            name="summary",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
