# Generated by Django 4.2 on 2024-10-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0015_alter_summary_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workexperiencebullets",
            name="bullet_point",
            field=models.CharField(max_length=210),
        ),
    ]
