# Generated by Django 4.2 on 2024-10-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0018_project_end_date_project_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
