# Generated by Django 4.2 on 2024-10-12 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contact_information", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinformation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contactinformation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
