version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      ["gunicorn", "--bind", "0.0.0.0:3003", "dynamiccv.wsgi:application"]
    ports:
      - "3003:3003"
    environment:
      - DJANGO_SETTINGS_MODULE=dynamiccv.settings
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3003/health/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - db
    networks:
      - coolify

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - coolify

volumes:
  postgres_data:

networks:
  coolify:
