# Generated by Django 4.2 on 2024-10-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_template", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvtemplate",
            name="cv_name",
            field=models.CharField(default="default", max_length=100),
        ),
    ]
