# Generated by Django 4.2 on 2024-10-13 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_remove_workexperience_present"),
        ("cv_template", "0002_cvtemplate_cv_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvtemplate",
            name="contact_information",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cv_contact_information",
                to="profiles.contactinformation",
            ),
        ),
        migrations.AddField(
            model_name="cvtemplate",
            name="education",
            field=models.ManyToManyField(
                related_name="cv_education", to="profiles.education"
            ),
        ),
        migrations.AddField(
            model_name="cvtemplate",
            name="skills",
            field=models.ManyToManyField(related_name="cv_skills", to="profiles.skill"),
        ),
        migrations.AddField(
            model_name="cvtemplate",
            name="use_default_summary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cvtemplate",
            name="work_experience",
            field=models.ManyToManyField(
                related_name="cv_work_experience", to="profiles.workexperience"
            ),
        ),
    ]
