# Generated by Django 4.2 on 2024-10-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_template", "0005_cvtemplate_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvtemplate",
            name="position_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
