# Generated by Django 4.2 on 2024-10-16 20:01

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cv_template", "0007_alter_cvtemplate_projects_cvanalysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvtemplate",
            name="color",
            field=colorfield.fields.ColorField(
                default="#6495ed", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
