# Generated by Django 4.2 on 2024-10-16 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_template", "0008_cvtemplate_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="BestPracticeCV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "summary_length",
                    models.CharField(
                        max_length=1000,
                        validators=[django.core.validators.MinLengthValidator(250)],
                    ),
                ),
                ("lower_bound", models.IntegerField()),
                ("upper_bound", models.IntegerField()),
                ("description", models.CharField(max_length=1000)),
            ],
        ),
    ]
