# Generated by Django 4.2 on 2024-10-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0017_hobby_additionalinformation"),
        ("cv_template", "0009_bestpracticecv"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvtemplate",
            name="extra_info",
            field=models.ManyToManyField(
                blank=True,
                related_name="cv_extra_info",
                to="profiles.additionalinformation",
            ),
        ),
        migrations.AddField(
            model_name="cvtemplate",
            name="hobbies",
            field=models.ManyToManyField(
                blank=True, related_name="cv_hobbies", to="profiles.hobby"
            ),
        ),
    ]
