# Generated by Django 4.2 on 2024-10-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_template", "0009_bestpracticecv"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvanalysis",
            name="suggested_roles",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
