# Generated by Django 4.2 on 2024-10-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_template", "0012_alter_cvtemplate_education_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvtemplate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="cvtemplate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
