# Generated by Django 4.2 on 2024-10-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_template", "0013_alter_cvtemplate_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvtemplate",
            name="item_ordering",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
